import turtle
screen=turtle.getscreen()
x=turtle.Turtle()
x.color('blue')
x.begin_fill()
x.circle(50)
x.forward(60)
x.color('orange')
x.circle(50)
x.forward(60)
x.color('black')
x.circle(50)
x.forward(60)
x.color('red')
x.circle(50)
x.forward(60)
screen.exitonclick()
